# Generated by Django 3.2.4 on 2021-06-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0002_auto_20210608_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='housband',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_of_women', to='familydataapp.member'),
        ),
    ]
