# Generated by Django 3.2.4 on 2021-06-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0004_auto_20210621_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='national_id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
