# Generated by Django 3.2.4 on 2021-06-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0007_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
