# Generated by Django 3.2.4 on 2021-06-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0011_alter_member_date_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('s', 'Unmarried')], default=None, max_length=1, null=True),
        ),
    ]
