# Generated by Django 3.2.4 on 2021-06-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0012_member_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='father',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of_father', to='familydataapp.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='housband',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wives', to='familydataapp.member'),
        ),
    ]
