# Generated by Django 3.2.4 on 2021-06-23 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0013_auto_20210623_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mother',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of_mother', to='familydataapp.member'),
        ),
    ]
