# Generated by Django 3.2.4 on 2021-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0017_alter_member_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('s', 'Unmarried')], default='Unmarried', max_length=1, null=True),
        ),
    ]
