# Generated by Django 3.2.4 on 2021-06-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0019_alter_member_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officer_name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=12)),
                ('office_name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('M', 'Married'), ('S', 'Unmarried')], default=None, max_length=1, null=True),
        ),
    ]
