# Generated by Django 3.2.4 on 2021-06-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0020_auto_20210627_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importantnumber',
            name='office_name',
        ),
    ]
