# Generated by Django 3.2.4 on 2021-06-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0021_remove_importantnumber_office_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=250)),
                ('place_type', models.CharField(choices=[('Mandir', 'Mandir'), ('Masjid', 'Masjid')], max_length=250)),
                ('chairman', models.CharField(blank=True, max_length=250, null=True)),
                ('vice_chairman', models.CharField(blank=True, max_length=250, null=True)),
                ('responsible_person_one', models.CharField(blank=True, max_length=250, null=True)),
                ('responsible_person_two', models.CharField(blank=True, max_length=250, null=True)),
                ('responsible_person_three', models.CharField(blank=True, max_length=250, null=True)),
                ('responsible_person_four', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
