# Generated by Django 3.2.4 on 2021-06-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0022_crimepoint_prayerplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('head_of_institution', models.CharField(blank=True, max_length=250, null=True)),
                ('head_contact_number', models.CharField(blank=True, max_length=250, null=True)),
                ('institution_contact_number', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
