# Generated by Django 3.2.4 on 2021-06-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0023_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institute_type',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College'), ('Madrasha', 'Madrasha'), ('University', 'University'), ('Kindergarten', 'Kindergarten')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
