# Generated by Django 3.2.4 on 2021-07-03 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('familydataapp', '0023_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('near_identity_one', models.CharField(blank=True, max_length=250, null=True)),
                ('near_identity_two', models.CharField(blank=True, max_length=250, null=True)),
                ('near_identity_three', models.CharField(blank=True, max_length=250, null=True)),
                ('near_identity_four', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_location', models.ManyToManyField(to='familydataapp.CrimePlace')),
            ],
        ),
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='CrimePoint',
        ),
        migrations.AddField(
            model_name='institution',
            name='institute_type',
            field=models.CharField(choices=[('School', 'School'), ('College', 'College'), ('Madrasha', 'Madrasha'), ('University', 'University'), ('Kindergarten', 'Kindergarten')], default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crimeteam',
            name='crime_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='familydataapp.crimetype'),
        ),
        migrations.AddField(
            model_name='crimeteam',
            name='member',
            field=models.ManyToManyField(to='familydataapp.Member'),
        ),
    ]
