# Generated by Django 3.2.4 on 2021-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0024_auto_20210703_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimeteam',
            name='crime_location',
            field=models.ManyToManyField(related_name='team_in_here', to='familydataapp.CrimePlace'),
        ),
    ]
