# Generated by Django 3.2.4 on 2021-07-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0025_alter_crimeteam_crime_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_criminal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
