# Generated by Django 3.2.4 on 2021-07-07 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familydataapp', '0026_member_is_criminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='familydataapp.division'),
        ),
        migrations.AlterField(
            model_name='member',
            name='blood_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='familydataapp.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='member',
            name='housband',
            field=models.ForeignKey(blank=True, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wives', to='familydataapp.member'),
        ),
    ]
